# Generated by Django 6.0.4 on 2026-04-19 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Nova conversa', max_length=200)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('alterada_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Conversa',
                'verbose_name_plural': 'Conversas',
                'ordering': ['-alterada_em'],
            },
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.CharField(choices=[('user', 'Utilizador'), ('assistant', 'Assistente')], max_length=10)),
                ('texto', models.TextField()),
                ('fontes', models.JSONField(default=list)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('conversa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='recuperacao.conversa')),
            ],
            options={
                'verbose_name': 'Mensagem',
                'ordering': ['criada_em'],
            },
        ),
    ]
