# Generated by Django 6.0.3 on 2026-05-10 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recuperacao', '0002_utilizador_conversa_utilizador'),
    ]

    operations = [
        migrations.CreateModel(
            name='FonteFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fonte_id', models.CharField(help_text='ID da fonte (ex: número do processo)', max_length=200)),
                ('relevancia', models.IntegerField(default=0, help_text='-1: Down, 0: Neutro, 1: Up')),
                ('removida', models.BooleanField(default=False)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('alterado_em', models.DateTimeField(auto_now=True)),
                ('mensagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='recuperacao.mensagem')),
            ],
            options={
                'verbose_name': 'Feedback de Fonte',
                'unique_together': {('mensagem', 'fonte_id')},
            },
        ),
    ]
