# Generated by Django 6.0.4 on 2026-04-19 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('ficheiro_js', models.CharField(max_length=200)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Template',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='PecaGerada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processo', models.CharField(blank=True, max_length=150)),
                ('trabalhador', models.CharField(blank=True, max_length=200)),
                ('gerada_em', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geracao.template')),
            ],
            options={
                'verbose_name': 'Peça Gerada',
                'ordering': ['-gerada_em'],
            },
        ),
    ]
