# Generated by Django 6.0.3 on 2026-05-09 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geracao', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='template',
            options={'ordering': ['nome_exibicao'], 'verbose_name': 'Template'},
        ),
        migrations.RemoveField(
            model_name='template',
            name='ficheiro_js',
        ),
        migrations.RemoveField(
            model_name='template',
            name='nome',
        ),
        migrations.AddField(
            model_name='template',
            name='identificador',
            field=models.SlugField(default='', help_text='ID interno (ex: contestacao)', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='template',
            name='nome_exibicao',
            field=models.CharField(default='', help_text='Nome que aparece na lista', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='template',
            name='nome_ficheiro_docx',
            field=models.CharField(default='', help_text='Nome do ficheiro .docx em pipeline/legal_docs/', max_length=200),
            preserve_default=False,
        ),
    ]
