# Generated by Django 6.0.3 on 2026-05-10 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geracao', '0002_alter_template_options_remove_template_ficheiro_js_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='campos',
            field=models.JSONField(blank=True, default=list, help_text='Marcadores {{...}} detectados no documento'),
        ),
    ]
