# Generated by Django 6.0.4 on 2026-04-19 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcordaoIndexado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_documento', models.CharField(db_index=True, max_length=64, unique=True)),
                ('processo', models.CharField(blank=True, max_length=150)),
                ('relator', models.CharField(blank=True, max_length=200)),
                ('tribunal_id', models.CharField(blank=True, max_length=20)),
                ('tribunal_nome', models.CharField(blank=True, max_length=200)),
                ('data_acordao', models.CharField(blank=True, max_length=20)),
                ('descritores', models.TextField(blank=True)),
                ('url', models.URLField(blank=True, max_length=500)),
                ('nome_html', models.CharField(blank=True, max_length=200)),
                ('nome_txt', models.CharField(blank=True, max_length=200)),
                ('n_chunks', models.IntegerField(default=0)),
                ('sumario', models.TextField(blank=True)),
                ('indexado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Acórdão Indexado',
                'verbose_name_plural': 'Acórdãos Indexados',
                'ordering': ['-indexado_em'],
            },
        ),
    ]
