# Generated by Django 6.0.3 on 2026-05-09 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcordaoChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indice', models.IntegerField(help_text='Ordem do fragmento no documento original')),
                ('texto', models.TextField()),
                ('seccao', models.CharField(blank=True, db_index=True, max_length=100)),
                ('acordao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks_texto', to='ingestao.acordaoindexado')),
            ],
            options={
                'verbose_name': 'Fragmento de Acórdão',
                'verbose_name_plural': 'Fragmentos de Acórdão',
                'ordering': ['acordao', 'indice'],
            },
        ),
    ]
