# from dataclasses import dataclass, field

# from embedder import Embedder
# from llm import LLM
# from prompt_builder import PromptBuilder
# from vector_store import VectorStore


# @dataclass
# class RetrievalResult:
#     """
#     Result of a single retrieval + generation cycle.

#     Attributes
#     ----------
#     question : The original question posed by the user.
#     answer   : The text generated by the LLM.
#     sources  : The chunks retrieved from the VectorStore and passed to
#                the LLM as context. Each entry is a dict with keys:
#                    text, metadata, score.
#     prompt   : The full prompt that was sent to the LLM. Included for
#                debugging and prompt quality evaluation.
#     """
#     question: str
#     answer:   str
#     sources:  list[dict] = field(default_factory=list)
#     prompt:   str = ""


# class Retriever:
#     """
#     Orchestrates the full query flow for the AIAA RAG pipeline.

#     Connects the four components required for answering a question:
#         Embedder      → converts the question to a vector
#         VectorStore   → finds the most relevant chunks
#         PromptBuilder → assembles question + chunks into a prompt
#         LLM           → generates the answer from the prompt

#     All four components are injected via the constructor so each can
#     be swapped independently without modifying this class.

#     Args:
#         embedder:       Embedder instance — must be the same model used
#                         during indexation (same vector space).
#         store:          VectorStore instance with indexed documents.
#         prompt_builder: PromptBuilder instance for prompt assembly.
#         llm:            LLM instance for text generation.
#         n_results:      Number of chunks to retrieve per query. Default: 5.
#         filters:        Optional metadata filters applied to every search,
#                         e.g. {"type": "ruling"} to restrict to rulings.

#     Example
#     -------
#         embedder = SentenceTransformerEmbedder("paraphrase-multilingual-MiniLM-L12-v2")
#         store    = ChromaStore(embedder=embedder)
#         builder  = LegalPromptBuilder()
#         llm      = OllamaLLM("mistral", temperature=0.0)

#         retriever = Retriever(embedder, store, builder, llm)
#         result    = retriever.ask("Qual o prazo para apresentar queixa em litígios laborais?")

#         print(result.answer)
#         for i, src in enumerate(result.sources, 1):
#             print(f"[{i}] score={src['score']:.2f}  {src['metadata']}")
#     """

#     def __init__(
#         self,
#         embedder:       Embedder,
#         store:          VectorStore,
#         prompt_builder: PromptBuilder,
#         llm:            LLM,
#         n_results:      int = 5,
#         filters:        dict | None = None,
#     ) -> None:
#         self._embedder       = embedder
#         self._store          = store
#         self._prompt_builder = prompt_builder
#         self._llm            = llm
#         self._n_results      = n_results
#         self._filters        = filters

#     # ------------------------------------------------------------------
#     # Public API
#     # ------------------------------------------------------------------

#     def ask(self, question: str) -> RetrievalResult:
#         """
#         Answer a question using the RAG pipeline.

#         Steps
#         -----
#         1. Embed the question.
#         2. Search the VectorStore for the most relevant chunks.
#         3. Build a prompt from the question and retrieved chunks.
#         4. Generate an answer with the LLM.
#         5. Return a RetrievalResult with answer, sources and prompt.

#         Args:
#             question: The user's question in natural language.

#         Returns:
#             RetrievalResult with answer, sources used, and full prompt.
#         """
#         # Step 1+2 — retrieve relevant chunks
#         # (VectorStore.search embeds the query internally using the same embedder)
#         chunks = self._store.search(
#             query=question,
#             filters=self._filters,
#             n=self._n_results,
#         )

#         # Step 3 — build prompt
#         prompt = self._prompt_builder.build(question, chunks)

#         # Step 4 — generate answer
#         answer = self._llm.generate(prompt)

#         return RetrievalResult(
#             question=question,
#             answer=answer,
#             sources=chunks,
#             prompt=prompt,
#         )
from dataclasses import dataclass, field

from embedder import Embedder
from llm import LLM
from prompt_builder import PromptBuilder
from vector_store import VectorStore


@dataclass
class RetrievalResult:
    """
    Result of a single retrieval + generation cycle.

    Attributes
    ----------
    question : The original question posed by the user.
    answer   : The text generated by the LLM.
    sources  : The chunks retrieved from the VectorStore and passed to
               the LLM as context. Each entry is a dict with keys:
                   text, metadata, score.
    prompt   : The full prompt that was sent to the LLM. Included for
               debugging and prompt quality evaluation.
    """
    question: str
    answer:   str
    sources:  list[dict] = field(default_factory=list)
    prompt:   str = ""


class Retriever:
    """
    Orchestrates the full query flow for the AIAA RAG pipeline.

    Connects the four components required for answering a question:
        Embedder      → converts the question to a vector
        VectorStore   → finds the most relevant chunks
        PromptBuilder → assembles question + chunks into a prompt
        LLM           → generates the answer from the prompt

    All four components are injected via the constructor so each can
    be swapped independently without modifying this class.

    Args:
        embedder:       Embedder instance — must be the same model used
                        during indexation (same vector space).
        store:          VectorStore instance with indexed documents.
        prompt_builder: PromptBuilder instance for prompt assembly.
        llm:            LLM instance for text generation.
        n_results:      Number of chunks to retrieve per query. Default: 5.
        filters:        Optional metadata filters applied to every search,
                        e.g. {"type": "ruling"} to restrict to rulings.

    Example
    -------
        embedder = SentenceTransformerEmbedder("paraphrase-multilingual-MiniLM-L12-v2")
        store    = ChromaStore(embedder=embedder)
        builder  = LegalPromptBuilder()
        llm      = OllamaLLM("mistral", temperature=0.0)

        retriever = Retriever(store, builder, llm)
        result    = retriever.ask("Qual o prazo para apresentar queixa em litígios laborais?")

        print(result.answer)
        for i, src in enumerate(result.sources, 1):
            print(f"[{i}] score={src['score']:.2f}  {src['metadata']}")
    """

    def __init__(
        self,
        store:          VectorStore,
        prompt_builder: PromptBuilder,
        llm:            LLM,
        n_results:      int = 5,
        filters:        dict | None = None,
    ) -> None:
        self._store          = store
        self._prompt_builder = prompt_builder
        self._llm            = llm
        self._n_results      = n_results
        self._filters        = filters

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def ask(self, question: str, n_results: int | None = None) -> RetrievalResult:
        """
        Answer a question using the RAG pipeline.

        Steps
        -----
        1. Embed the question.
        2. Search the VectorStore for the most relevant chunks.
        3. Build a prompt from the question and retrieved chunks.
        4. Generate an answer with the LLM.
        5. Return a RetrievalResult with answer, sources and prompt.

        Args:
            question:  The user's question in natural language.
            n_results: Optional override for the number of chunks to retrieve.

        Returns:
            RetrievalResult with answer, sources used, and full prompt.
        """
        # Step 1+2 — retrieve relevant chunks
        # (VectorStore.search embeds the query internally using the same embedder)
        chunks = self._store.search(
            query=question,
            filters=self._filters,
            n=n_results or self._n_results,
        )

        # Step 3 — build prompt
        prompt = self._prompt_builder.build(question, chunks)

        # Step 4 — generate answer
        answer = self._llm.generate(prompt)

        return RetrievalResult(
            question=question,
            answer=answer,
            sources=chunks,
            prompt=prompt,
        )